#!/usr/bin/env bash
help () {
    echo "                              Emetshaf Automation Tool"
    echo -e "Automation tool for EMetshaf\n"
    echo -e "Usage: setup <command> [arguments]\n"
    echo "Global options:"
    echo -e "-h, --help          Print this usage information.\n"
    echo "Available commands:"
    echo "  env         setup environment variables."
    echo "  docker      Setup Docker containers."
}

help_env () {
    echo -e "Usage: setup env <subcommand> [arguments]\n"
    echo "Global options:"
    echo -e "-h, --help          Print this usage information.\n"
    echo "Available commands:"
    echo "  prod      set environment variables to production."
    echo "  dev       set environment variables to development."
    echo "  test      set environment variables to testing."
}

help_docker () {
    echo -e "Usage: setup docker <subcommand> [arguments]\n"
    echo "Global options:"
    echo -e "-h, --help          Print this usage information.\n"
    echo "Available commands:"
    echo "  build      build docker image."
    echo "  run        run docker container."
}

if [ "$1" == "--help" ] || [ "$1" == '-h' ] || [ "$1" == "help" ]
then
    help
elif [ "$1" == "env" ]
then
    if [ "$2" == "--help" ] || [ "$2" == '-h' ] || [ "$2" == "help" ]
    then
        help_env
    elif [[ "$2" == "prod" ]]
    then
        export EMETSHAF_ENV=prod EMETSHAF_MYSQL_USER=emetshaf_prod EMETSHAF_MYSQL_PWD=emetshaf_prod_pwd EMETSHAF_MYSQL_HOST=localhost EMETSHAF_MYSQL_DB=emetshaf_prod_db
        echo "EMETSHAF_ENV=$EMETSHAF_ENV"
    elif [[ "$2" == "dev" ]]
    then
        export EMETSHAF_ENV=dev EMETSHAF_MYSQL_USER=emetshaf_dev EMETSHAF_MYSQL_PWD=emetshaf_dev_pwd EMETSHAF_MYSQL_HOST=localhost EMETSHAF_MYSQL_DB=emetshaf_dev_db
        echo "EMETSHAF_ENV=$EMETSHAF_ENV"
    elif [[ "$2" == "test" ]]
    then
        export EMETSHAF_ENV=test EMETSHAF_MYSQL_USER=emetshaf_test EMETSHAF_MYSQL_PWD=emetshaf_test_pwd EMETSHAF_MYSQL_HOST=localhost EMETSHAF_MYSQL_DB=emetshaf_test_db
        echo "EMETSHAF_ENV=$EMETSHAF_ENV"
    else
        help_env
    fi
elif [ "$1" == "docker" ]
then
    if [ "$2" == "--help" ] || [ "$2" == '-h' ] || [ "$2" == "help" ]
    then
        help_docker
    elif [ "$2" == "build" ]
    then
        docker build -t emetshaf/api .
        docker build -t emetshaf/web ./web
    elif [ "$2" == "run" ]
    then
        docker run -d -it -p 5000:5000 emetshaf/api
        docker run -d -it -p 8080:8080 emetshaf/web
    else
        help_docker
    fi
else
    help
fi
